services:
  db:
    image: mongo:latest
    ports: 
      - "27017:27017"
    volumes:
      - "data-vol:/data/db"

  api:
    image: akri16/yt_publisher:latest

    depends_on:
      - db
    ports:
      - "8000:8000"

    environment:
      - MONGO_CONN_STR=mongodb://db:27017/yt_db
      - YT_API_KEYS=${YT_API_KEYS}

    command: 'api'

  poller:
    image: akri16/yt_publisher:latest
    
    environment:
      - MONGO_CONN_STR=mongodb://db:27017/yt_db
      - POLL_INTERVAL=10
      - YT_API_KEYS=${YT_API_KEYS}
      - POLL_QUERY=surfing
      - POLL_MAX_RES=25
    
    depends_on:
      - db

    command: 'poller'

volumes:
  data-vol: